package ir.maktabsharif;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class CalculatorTest {
    @Test
    public void shouldAnswerWithTrue() {
        assertTrue(true);
    }
   /* Phase 1
Entity Design
Create an entity named "Appointment".
Your entity should contain at least the following fields:
• id
• patientName
• patientNationalCode
• patientPhoneNumber
• doctorName

• appointmentDate
• appointmentTime
• visitPrice
• trackingCode
• status
• createdAt
Create an enum named "AppointmentStatus" with the following values:
• RESERVED
• COMPLETED
• CANCELLED
• MISSED
Use an "@Embedded" class to store audit information.
Challenge
Decide the following by yourself:
• Which fields should be unique?
• Which fields should not allow null values?
• Should the "trackingCode" be generated by the system or provided by the user?
Explain your decision.*/
}

